server:
  port: 7071

spring:
  application:
    name: shop-member-server
  # ======= 数据源 =======
  datasource:
    name: idea-shop-db
    url: jdbc:mysql://localhost:3306/shop_member?setUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  # ======= redis =======
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timeout: 1000ms
    lettuce:
      pool:
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
  cloud:
    # ======= 注册中心 =======
    nacos:
      discovery:
        server-addr: localhost:8848

# ======= mybatis-plus =======
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.quaint.demo.mybatis.plus.po
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 配置逻辑删除
  global-config:
    db-config:
      logic-delete-value: 0
      logic-not-delete-value: 1

# ======= 日志输出级别 TRACE > DEBUG > INFO > WARN > ERROR =======
logging:
  #系统日志文件输出地址
  path: ./logs
  #系统日志输出级别
  #sys系统输出将过滤器的日志级别配置为level
  sys:
    level: INFO
  #console控制台打印日志将当日志级别等于或高于临界值时
  console:
    level: INFO